# Generated by Django 3.2.12 on 2022-02-27 08:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='10-200 символов', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Наименование')),
                ('alias', models.CharField(help_text='5-50 символов', max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Короткое наименование')),
                ('description', models.TextField(blank=True, default='', help_text='0-1000 символов', max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'справочник',
                'verbose_name_plural': 'справочники',
            },
        ),
        migrations.CreateModel(
            name='DirectoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='1-100 символов. Должна быть уникальна в пределах справочника', max_length=100, verbose_name='Версия справочника')),
                ('actual_from_dt', models.DateField(verbose_name='Дата начала действия версии')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', related_query_name='version', to='app_terms.directory', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'версия справочника',
                'verbose_name_plural': 'версии справочника',
                'ordering': ('-actual_from_dt',),
            },
        ),
        migrations.CreateModel(
            name='DirectoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='1-100 символов. Должен быть уникален в пределах сравочника', max_length=100, verbose_name='Код')),
                ('value', models.TextField(help_text='1-1000 символов', max_length=1000, verbose_name='Значение элемента')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='app_terms.directory', verbose_name='Справочник')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='app_terms.directoryversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'элемент справочника',
                'verbose_name_plural': 'элементы справочника',
            },
        ),
        migrations.AddConstraint(
            model_name='directoryversion',
            constraint=models.UniqueConstraint(fields=('directory', 'version'), name='app_terms_directoryversion_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='directoryversion',
            constraint=models.UniqueConstraint(fields=('directory', 'actual_from_dt'), name='app_terms_directoryversion_unique_actual_from_dt'),
        ),
        migrations.AddConstraint(
            model_name='directoryitem',
            constraint=models.UniqueConstraint(fields=('directory', 'code'), name='app_terms_directoryitem_unique_code'),
        ),
    ]
