# Generated by Django 3.2.12 on 2022-02-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoryitem',
            options={'ordering': ('code',), 'verbose_name': 'элемент справочника', 'verbose_name_plural': 'элементы справочника'},
        ),
    ]
