# Generated by Django 3.2.12 on 2022-02-28 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_terms', '0002_alter_directoryitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='title',
            field=models.CharField(help_text='10-200 символов. Должно быть уникально', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Наименование'),
        ),
    ]
