# Generated by Django 3.2.12 on 2022-02-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_terms', '0003_alter_directory_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ('title',), 'verbose_name': 'справочник', 'verbose_name_plural': 'справочники'},
        ),
    ]
